name: plowth_app
description: "AI-powered learning operating system"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  dio: ^5.7.0
  shared_preferences: ^2.3.4
  drift: ^2.31.0
  sqlite3_flutter_libs: ^0.5.42
  path: ^1.9.1
  path_provider: ^2.1.5
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.31.0
  build_runner: ^2.13.1

flutter:
  uses-material-design: true
